# Makefile
PYTHON_BIN = python3

all: prod-venv ## Build complete environment

.PHONY: help
help: # Display help
	@awk -F ':|##' \
		'/^[^\t].+?:.*?##/ {\
			printf "\033[36m%-30s\033[0m %s\n", $$1, $$NF \
		}' $(MAKEFILE_LIST)

prod-venv: .venv/bin/activate ## Build prod (i.e. no poetry) virtual environment

.venv/bin/activate: requirements.txt
	if [ ! -d .venv ]; then \
		$(PYTHON_BIN) -m venv .venv; \
	fi
	.venv/bin/pip install --require-hashes -r requirements.txt

.PHONY: install
install:
	which -s poetry || (echo "You need 'poetry' (https://python-poetry.org/) to run this"; exit 1)
	@poetry install

.PHONY: generate-requirements
generate-requirements: requirements.txt install ## Regenerate requirements.txt from requirements-base.txt
	echo "# Autogenerated file, do not modify; see pyproject.toml" > requirements.txt
	@poetry export -f requirements.txt >> requirements.txt

.PHONY: format
format: install
	@poetry run black *.py
	@poetry run isort *.py

.PHONY: clean
clean: ## Delete all generated artefacts
	$(RM) -rf .venv venv
	find . -name "*.pyc" -exec $(RM) -rf {} \;
